### ISSUE TITLE
Feedback on Section 3 WIP: Testing of a Graph Framework (1st priority)

### ISSUE THREAD

**Issue by annielytical** [owensgroup/Robison_Gunrock_Report#2]
[Here is the link to my report PDF.](https://github.com/owensgroup/Robison_MS_Project_Report/blob/c03c8bb72a48636f7408d5447f759b4b1cdf93cf/report.pdf)

Section 3: Testing of a Graph Framework
3.1 - Metrics
- Are all necessary metrics included?

3.2 - Methods
- Do you think the discussion of what we did initially (not our final implementation) is useful?
- Is there any part of the implementation that is confusing / does not seem to be well-explained?

**Comment by jowens** [comment]
I'm thinking out loud about how to organize this. I think a "design" chapter and an "implementation" chapter make sense.

Start the design chapter with "requirements". What info does your framework need to collect? (That's your "Metrics" section.) But also, what other requirements might it have? For instance, you'd like it to have good performance even when it's collecting metrics, so "minimal runtime overhead". You also appear to want two modes of operation, and that's your "methods" section. The "design" chapter should also include a description of big-picture design decisions that you made (for instance, what is done at compile-time and what is done at runtime).

You can make "implementation details" a section within "design". The goals are to talk about particularly interesting or difficult details that you had to address when you were actually implementing the framework. Besides that, let's say your work was all deleted and you had to explain to someone else how that person might implement it again from scratch. What would you want to tell that person?

For "Analysis", rather than think about what _could_ you measure and just dumping in a bunch of graphs that measure everything possible, think about what you are trying to show with your work. What points are you trying to make? What insights will your measurements give? You want this section to support your thesis ("thesis" defined as it was in the comment re: the previous chapter), and the analysis should _directly_ support this thesis. I can offer more comments once you take a first pass at your thesis.
