### ISSUE TITLE
 Feedback on Section 2 WIP: Programmability of a Graph Framework (2nd priority)

### ISSUE THREAD

**Issue by annielytical** [owensgroup/Robison_Gunrock_Report#3]
[Here is the link to my report PDF.](https://github.com/owensgroup/Robison_MS_Project_Report/blob/c03c8bb72a48636f7408d5447f759b4b1cdf93cf/report.pdf)

Section 2: Programmability of a Graph Framework
2.1 - Graph Representations
- Do the examples and explanations make sense?

**Comment by jowens** [comment]
The title doesn't match what you discuss in Section 2.0. The title talks about programmability. Section 2.0 (which is traditionally used as an intro/summary of a chapter) talks about data structures.

## CSR/CSC

The description of these formats is perfectly good, but it's also well-known. I don't want you to spend your time writing things that are already well-known. If you're writing about something that's already on Wikipedia, you probably don't have to write it. You can cite prior work so that you don't have to write it up yourself. This is accepted practice and important for you to do. 

What is instead important for you to discuss is _why_ CSR/CSC are important for Gunrock. That is something that is NOT discussed on Wikipedia. Why did we pick CSR/CSC? What is good/bad about them from the point of view of GPU parallelism, from fine-grained load balancing, from GPU memory performance (e.g., coalescing)? If you're going to write about CSR/CSC, that's where you want to spend your effort. Eventually you will write about what you are measuring (specifically) and I would expect you to cite back to this section. You want to introduce CSR/CSC background _only_ to support points you will make later in the paper.

## Graph properties

These are more interesting to talk about than CSR/CSC (because CSR/CSC are already well known). What would be interesting for me to know as a reader (for each of these) is two things: (1) how do these properties relate to actual graphs found in the real world (like, are most graphs symmetric/not? directed/not?), and (2) how do these properties relate to Gunrock's implementation (for instance, how do you process a graph differently if it is directed vs. undirected, what kind of optimizations can you apply?).

## Methods

I'm not sure how this subsection relates to the other two, which are mostly "background/prior work". It is common, and makes sense in your case, that the _design_ of the system you have built will be its own chapter, and then separately, a chapter on the _implementation_ of your designed system.
